name: Publish packages

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    container: node:latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: kodex
          POSTGRES_USER: kodex
          POSTGRES_PASSWORD: kodex
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-node@v2
        name: Install node
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'

      - run: yarn
        name: Install dependencies

      - run: yarn bootstrap
        name: Bootstrap with Lerna

      - run: yarn build
        name: Build packages

      - run: yarn test
        name: Testing packages
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432

      #- run: yarn lerna publish
      #  name: Publish to repo
