name: Publish packages

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    container: node:latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: kodex
          POSTGRES_USER: kodex
          POSTGRES_PASSWORD: kodex
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@uminily'

      - name: Config git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install dependencies
        run: yarn

      - name: Bootstrap with Lerna
        run: yarn bootstrap

      - name: Build packages
        run: yarn build

      - name: Testing packages
        run: yarn test
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432

      - name: Publish to repo
        run: |
          yarn version:ci
          yarn publish:ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  clean-injection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v1
        with:
          package-name: 'injection'
          num-old-versions-to-delete: 1

  clean-common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v1
        with:
          package-name: 'common'
          num-old-versions-to-delete: 1

  clean-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v1
        with:
          package-name: 'config'
          num-old-versions-to-delete: 1

  clean-errors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v1
        with:
          package-name: 'errors'
          num-old-versions-to-delete: 1

  clean-mikro-orm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v1
        with:
          package-name: 'mikro-orm'
          num-old-versions-to-delete: 1

  clean-crud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v1
        with:
          package-name: 'crud'
          num-old-versions-to-delete: 1

  clean-logger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v1
        with:
          package-name: 'logger'
          num-old-versions-to-delete: 1
